import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "../styles/globals.css";

/**
 * Self-hosted via next/font (downloaded at build time, served same-origin).
 * `variable` props declare --font-sans / --font-mono on <html>; the @theme
 * fallback stacks in globals.css resolve through these vars at runtime, so
 * `font-sans`/`font-mono` utilities and the body font-family hit the real
 * loaded faces. Design rule: terminal/waybar/launcher use font-mono, body
 * uses font-sans.
 */
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-sans",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
