#!/usr/bin/env node
/** Batch-convert public raster assets to WebP under each folder's optimized/ subdir. */
import { execSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join, extname, basename, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const manifestPaths = [];

const presets = [
  {
    label: "wallpapers",
    inDir: join(root, "public/Wallpaper"),
    outDir: join(root, "public/Wallpaper/optimized"),
    filter: (f) => !f.startsWith("optimized") && /\.(png|jpe?g|webp)$/i.test(f),
    magick: "-resize 1920x1080^ -gravity center -extent 1920x1080 -strip -quality 80",
  },
  {
    label: "pictures",
    inDir: join(root, "public/pictures"),
    outDir: join(root, "public/pictures/optimized"),
    filter: (f) => !f.startsWith("optimized") && /\.(png|jpe?g)$/i.test(f),
    magick: "-resize 1200x1200> -strip -quality 82",
  },
  {
    label: "images",
    inDir: join(root, "public/images"),
    outDir: join(root, "public/images/optimized"),
    filter: (f) =>
      !f.startsWith("optimized") &&
      f !== "lockscreen-opt.webp" &&
      /\.(png|jpe?g)$/i.test(f),
    magick: "-resize 1600x1600> -strip -quality 82",
  },
];

function safeBase(name) {
  return name.replace(/\s+/g, "-");
}

function convert(src, dest, magickArgs) {
  mkdirSync(dirname(dest), { recursive: true });
  execSync(`magick "${src}" ${magickArgs} -- "${dest}"`, { stdio: "inherit" });
}

for (const preset of presets) {
  if (!existsSync(preset.inDir)) {
    console.warn("skip missing", preset.inDir);
    continue;
  }
  mkdirSync(preset.outDir, { recursive: true });
  for (const file of readdirSync(preset.inDir).filter(preset.filter)) {
    const base = safeBase(basename(file, extname(file)));
    const dest = join(preset.outDir, `${base}.webp`);
    convert(join(preset.inDir, file), dest, preset.magick);
    console.log(`[${preset.label}] ${file} → optimized/${base}.webp`);
    if (preset.label === "wallpapers") {
      manifestPaths.push(`/Wallpaper/optimized/${base}.webp`);
    }
  }
}

if (manifestPaths.length) {
  manifestPaths.sort((a, b) => a.localeCompare(b));
  const outFile = join(root, "src/generated/wallpaper-manifest.js");
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(
    outFile,
    `/** Auto-generated by scripts/optimize-images.mjs — do not edit */\nexport const OPTIMIZED_WALLPAPER_PATHS = ${JSON.stringify(manifestPaths, null, 2)};\n`,
  );
  console.log(`Wrote ${manifestPaths.length} paths → src/generated/wallpaper-manifest.js`);
}

console.log("Done — serve only /Wallpaper/optimized, /pictures/optimized, /images/optimized WebP paths.");
