import { getAppIcon } from "./appIcons.js";

/** macOS-style icons — delegates to the central app icon registry. */
export const MAC_ICONS = {
  finder: getAppIcon("Finder"),
  safari: getAppIcon("Safari"),
  messages: getAppIcon("Messages"),
  mail: getAppIcon("Mail"),
  maps: getAppIcon("Maps"),
  photos: getAppIcon("Photos"),
  facetime: getAppIcon("FaceTime"),
  phone: getAppIcon("Phone"),
  calendar: getAppIcon("Calendar"),
  contacts: getAppIcon("Contacts"),
  notes: getAppIcon("Notes"),
  reminders: getAppIcon("Reminders"),
  music: getAppIcon("Music"),
  settings: getAppIcon("Settings"),
  trash: getAppIcon("Trash"),
  launchpad: getAppIcon("Launchpad"),
  textEdit: getAppIcon("TextEdit"),
  preview: getAppIcon("PDFViewer"),
  terminal: getAppIcon("Terminal"),
  folder: getAppIcon("Finder"),
  github: getAppIcon("Github"),
  linkedin: getAppIcon("linkedin"),
  appStore: getAppIcon("AppStore"),
  pages: getAppIcon("Pages"),
  numbers: getAppIcon("Numbers"),
  keynote: getAppIcon("Keynote"),
  podcasts: getAppIcon("Podcasts"),
  tv: getAppIcon("TV"),
};

export const ZAID_ICONS = {
  about: getAppIcon("About"),
  projects: getAppIcon("Projects"),
  articles: getAppIcon("Articles"),
  experience: getAppIcon("Experience"),
  resume: getAppIcon("Resume"),
  skills: getAppIcon("Skills"),
  chat: getAppIcon("ZaidGPT"),
  contact: getAppIcon("Contact"),
  chess: getAppIcon("Chess"),
  terminal: getAppIcon("Terminal"),
};
